routes/web.php
<?php

use App\Http\Controllers\LikeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\CommentsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [\App\Http\Controllers\PagesController::class, 'index'])->name('home');
Route::resource('/blog', \App\Http\Controllers\PostsController::class);
Route::get('/livewire', [\App\Http\Controllers\PostsController::class,'livewire'])->name('livewire');
Auth::routes();
Route::get('/search', '\App\Http\Controllers\PostsController@search')->name('search');
Route::get('/newestPosts', '\App\Http\Controllers\PostsController@newestPosts')->name('newestPosts');
Route::get('/mostLikedPosts', '\App\Http\Controllers\PostsController@mostLikedPosts')->name('mostLikedPosts');
Route::get('/mostViewedPosts', '\App\Http\Controllers\PostsController@mostViewedPosts')->name('mostViewedPosts');
Route::get('/postsByUsers', '\App\Http\Controllers\PostsController@postsByUsers')->name('postsByUsers');
Route::get('/{category}','App\Http\Controllers\PostsController@showCategory')->name('showCategory');
Route::post('blog/like/{id}', [LikeController::class,'likePost'])->name('post.like');
Route::post('/blog/{post}/comments',[CommentsController::class,'store']);
Route::delete('/blog/{post}/comments/delete/{comment_id}',[CommentsController::class,'destroy']);

app/Http/Livewire/Comments.php
<?php

namespace App\Http\Livewire;

use App\Model\Post;
use App\Models\Comment;
use Livewire\Component;
use Livewire\WithPagination;

class Comments extends Component
{

    public function render()
    {
        return view('livewire.comments',[
        ]);
    }


}

app/Http/Livewire/Search.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Post;
class Search extends Component
{
    public $query='';
    public $results;
    protected $queryString=['query'=>['except'=>'']];

    public function mount()
    {
        $this->reset();
    }
    public function render()
    {
           $this->results=Post::where('title','like',"%{$this->query}%")->get();

        return view('livewire.search');
    }
}

resources/views/livewire/comments.blade.php
<div>
    <div class="mt-6">
        @foreach($post->comments as $comment)

            <div class="flex">
                <div class="flex flex-col justify-center">

                    <p class="mt-4 font-bold italic text-gray-800">{{ $comment->user->name }}</p>
                    <p class="text-gray-600">{{$comment->created_at->diffForHumans()}}</p>
                </div>

            </div>

            <div class="mt-3">

                <p>{{$comment->text}}</p>
                @if (isset(Auth::user()->id) && Auth::user()->id == $comment->user_id)
                <form action="/blog/{{$post->slug}}/comments/delete/{{$comment->id}}" method="POST" class="mb-4 mt-3">
                    @csrf
                    @method('delete')
                    <button type="submit" class="text-sm py-1 px-2 border border-blue-400 shadow-sm rounded-md hover:shadow-md">Delete</button>
                </form>
            </div>
            @endif
        @endforeach
{{--            <a wire:click="load" class="btn btn-primary">Load more...</a>--}}
         {{--   {{ $post->comments->links("livewire.tailwind")}}--}}
    </div>
</div>

resources/views/livewire/search.blade.php
<div class="relative mt-3 md:mt-0">

    <form
        class=" mr-6  uppercase bg-transparent text-black text-xs font-extrabold font-extrabold rounded-3x" autocomplete="off"
        method="GET" action="{{url('/search')}}">
        <input wire:model="query" type="text" class=" px-8 py-2 w-80 rounded-xl " name="query"
               placeholder="Search...">

        <button class=" p-2.5 px-8 text-white bg-blue-700 rounded-3xl text-xs font-extrabold ">
            Search
        </button>
    </form>
   {{-- <input wire:model="query" type="text" class="bg-gray-800 text-sm rounded py-2 w-64 px-4 pl-8 focus:outline-none focus:shadow-outline"    placeholder="Search..."  />
--}}



    <div class="absolute top-0">
        <svg class="fill-current w-4 text-gray-500 mt-2 ml-2" viewBox="0 0 24 24"><path class="heroicon-ui" d="M16.32 14.9l5.39 5.4a1 1 0 01-1.42 1.4l-5.38-5.38a8 8 0 111.41-1.41zM10 16a6 6 0 100-12 6 6 0 000 12z" /></svg>
    </div>
    @if(strlen($query)>2)
    <div class="z-50 absolute bg-gray-800 text-sm rounded w-80 mt-4 " x-show.transition.opacity="isOpen">
        @if($results->count()>0)
        <ul>
            @foreach($results as $result)
            <li class="border-b border-gray-700">
                <a href="{{route('blog.show',$result->slug)}}" class="block hover:bg-gray-700 text-gray-200 px-3 py-3 items-center transition ease-in-out duration-150">
                    <span class="mt-4">{{$result->title}}</span>
                </a>
            </li>

            @endforeach
        </ul>
            @else
        <div class="m-2 p-2 text-gray-50">
            No results
        </div>
        @endif
    </div>
        @endif

</div>